### ISSUE TITLE
Metadata Document Generator - Enhancement: Excel export into single sheet

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/MsCrmTools.MetadataDocumentGenerator#1]
@AlexMcLachlan commented on [Thu Aug 10 2017](https://github.com/MscrmTools/XrmToolBox/issues/662)

Hi, 
I've used this really handy tools several times and end up wanting all the results combined in a single sheet and having to do this via macros.
Would it be possible to add an option for export to Excel to do this please?
A couple of additional columns at the start with entity display name and entity logical name can then be used to filter the sheet as appropriate.
All the best, Alex

---

@MscrmTools commented on [Mon Aug 14 2017](https://github.com/MscrmTools/XrmToolBox/issues/662#issuecomment-322108457)

What plugin are you talking about??

---

@AlexMcLachlan commented on [Mon Aug 14 2017](https://github.com/MscrmTools/XrmToolBox/issues/662#issuecomment-322111373)

Sorry - the Metadata Document Generator

**Comment by donalmc** [comment]
Hi, can I second this feature request?
I am trying to work out exactly how many Rollups I have in the one instance. 
Having the option to consolidate all the entities on a single worksheet would make this much easier.
