### ISSUE TITLE
generate for option not working

### ISSUE THREAD

**Issue by StephaneSeguin** [MscrmTools/MsCrmTools.MetadataDocumentGenerator#10]
The generate for option:  Not mather the option I select the List is always empty.
All attributes NOT contained in forms does'nt show any Forms in the list and the end result is the entities tab are generated but not attributes exported.

**Comment by MscrmTools** [comment]
You need to select the option, then select (not tick) an entity to display forms (see picture below)

![image](https://user-images.githubusercontent.com/10774317/71265832-64dbd480-2347-11ea-928b-6e3b5d19ee6b.png)
