### ISSUE TITLE
Enhancement - Add a filter for 'Unmanaged' attributes only

### ISSUE THREAD

**Issue by rlemmen** [MscrmTools/MsCrmTools.MetadataDocumentGenerator#11]
Hi Tanguy & XrmToolbox team,

The metadata document generator is already very helpful. With a filter option to only export unmanaged attributes it could be very helpful for documenting the work done in an implementation. Could you add that feature?

Thanks!

**Comment by MscrmTools** [comment]
Hi and thanks for this request, that can be implemented quite easily

**Comment by rlemmen** [comment]
Awesome, thanks!!
