### ISSUE TITLE
Issue With Meta Data Document Generator.

### ISSUE THREAD

**Issue by manas3487** [MscrmTools/MsCrmTools.MetadataDocumentGenerator#12]
[Write your comment/feedback/issue here]
Issue With Meta Data Document Generator. Unable to Complete it 100%. Every time this is failing.
Please let me know i can resolve the issue please.

![image](https://user-images.githubusercontent.com/35729553/85406759-e115d580-b57f-11ea-8873-81e18c61cd30.png)

---
- Deployment: Online
- DB Version: 9.1.0.18940
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 1.2019.5.1

**Comment by MscrmTools** [comment]
May I know what kind of entities you are trying to export? is there any special field (multi optionset?)

**Comment by manas3487** [comment]
Hi Yes there are most of the fields are multioptionsets,Global optionsets, etc. But never this has failed like this before :(. Could you please help in generating the Document please?

**Comment by msnow45** [comment]
Hi,
I have run into the same error message.  I tracked down I can have every thing selected except for the following
Entity: Solution Component Configuration, Attribute: Displayable, isdisplayable

**Comment by msnow45** [comment]
Have an idea it is because Microsoft does not provide label values for that attribute.
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/reference/entities/solutioncomponentconfiguration#BKMK_isdisplayable

**Comment by MscrmTools** [comment]
@msnow45 thank you for the feedback, it helped a lot
Fix on its way
