### ISSUE TITLE
Abilty to generate document based on entities/attributes in solution

### ISSUE THREAD

**Issue by bennyboy23** [MscrmTools/MsCrmTools.MetadataDocumentGenerator#21]
Hey, wondering if this possible, could we filter what entities / attributes we want to be generated, be driven entirely from a solution instead?

**Comment by MscrmTools** [comment]
That might be added yes

**Comment by MscrmTools** [comment]
Well, it already exists for solution driven
![image](https://user-images.githubusercontent.com/10774317/201674902-23f70ee7-6d7d-44ab-8e1f-028ee47793ed.png)
