### ISSUE TITLE
Object Type Code Incorrect for Custom Tables

### ISSUE THREAD

**Issue by donalmc** [MscrmTools/MsCrmTools.MetadataDocumentGenerator#22]
The Object Type Codes on the Entities list tab for custom entities do not match the codes available in a query - see query URL below (note - this is for an EU data tenant).

https://[YOUR LOCAL URL].api.crm4.dynamics.com/api/data/v9.1/EntityDefinitions?$select=LogicalName,ObjectTypeCode

(Thanks again for this great tool - especially the one sheet feature!)

**Comment by MscrmTools** [comment]
I would say that is just not possible since all info comes from Dataverse database...

But it could be the case for custom tables if you look at two different environments with the same custom tables as objecttypecode depends on the creation order
